sudo: required
services:
  - docker

before_install:
  - docker build -t danielblythe/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true danielblythe/react-test npm test

after_success:
  - docker build -t danielblythe/multi-client ./client
  - docker build -t danielblythe/multi-nginx ./nginx
  - docker build -t danielblythe/multi-server ./server
  - docker build -t danielblythe/multi-worker ./worker
  # Login to docker CLI
  - echo '$DOCKER_PASSWORD' | docker login -u '$DOCKER_ID' --password-stdin
  # Take those images and push them to docker hub
  - docker push danielblythe/multi-client
  - docker push danielblythe/multi-nginx
  - docker push danielblythe/multi-server
  - docker push danielblythe/multi-worker
